//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminEdificios
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departamentos
    {
        public Departamentos()
        {
            this.Propietarios = new HashSet<Propietarios>();
            this.Visitas = new HashSet<Visitas>();
            this.GastosPropiedades = new HashSet<GastosPropiedades>();
            this.Reservas = new HashSet<Reservas>();
        }
    
        public int DepartamentoId { get; set; }
        public int Piso { get; set; }
        public string Orientacion { get; set; }
        public string Tipo { get; set; }
        public string Cocina { get; set; }
        public int Metros { get; set; }
        public Nullable<decimal> Alicuota { get; set; }
    
        public virtual ICollection<Propietarios> Propietarios { get; set; }
        public virtual ICollection<Visitas> Visitas { get; set; }
        public virtual ICollection<GastosPropiedades> GastosPropiedades { get; set; }
        public virtual ICollection<Reservas> Reservas { get; set; }
    }
}
