//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminEdificios
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estacionamientos
    {
        public Estacionamientos()
        {
            this.Propietarios = new HashSet<Propietarios>();
            this.Visitas = new HashSet<Visitas>();
        }
    
        public int EstacionamientoId { get; set; }
        public int Piso { get; set; }
        public string Tipo { get; set; }
        public string Estado { get; set; }
    
        public virtual ICollection<Propietarios> Propietarios { get; set; }
        public virtual ICollection<Visitas> Visitas { get; set; }
    }
}
