//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminEdificios
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class admedifEntities : DbContext
    {
        public admedifEntities()
            : base("name=admedifEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Departamentos> Departamentos { get; set; }
        public virtual DbSet<Estacionamientos> Estacionamientos { get; set; }
        public virtual DbSet<Propietarios> Propietarios { get; set; }
        public virtual DbSet<Visitas> Visitas { get; set; }
        public virtual DbSet<GastosComunes> GastosComunes { get; set; }
        public virtual DbSet<GastosPropiedades> GastosPropiedades { get; set; }
        public virtual DbSet<Reservas> Reservas { get; set; }
    }
}
