//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminEdificios
{
    using System;
    using System.Collections.Generic;
    
    public partial class Propietarios
    {
        public int PropietarioId { get; set; }
        public string Nombre { get; set; }
        public string ApellidoP { get; set; }
        public string ApellidoM { get; set; }
        public string Rut { get; set; }
        public Nullable<int> Depto { get; set; }
        public Nullable<int> Estacionamiento { get; set; }
        public Nullable<int> TelFijo { get; set; }
        public Nullable<int> TelTrabajo { get; set; }
        public Nullable<int> TelCelular { get; set; }
    
        public virtual Departamentos Departamentos { get; set; }
        public virtual Estacionamientos Estacionamientos { get; set; }
    }
}
