//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;

namespace AdminEdificios
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visitas
    {
        public int VisitaId { get; set; }
        
        [Required(ErrorMessage="Ingresar Nombre")]
        [StringLength(20, MinimumLength = 3, ErrorMessage = "Nombre invalido")]
        public string Nombre { get; set; }

        [Required(ErrorMessage = "Ingresar Apellido Paterno")]
        [StringLength(20, MinimumLength = 3, ErrorMessage = "Apellido invalido")]
        public string ApellidoP { get; set; }

        [Required(ErrorMessage = "Ingresar Apellido Materno")]
        [StringLength(20, MinimumLength = 3, ErrorMessage = "Apellido invalido")]
        public string ApellidoM { get; set; }

        [Required(ErrorMessage = "Ingresar Rut")]
        [StringLength(9, MinimumLength = 8, ErrorMessage = "Rut invalido")]
        public string Rut { get; set; }

        [Required(ErrorMessage = "Ingresar Departamento de destino")]
        [Range(100, 999, ErrorMessage="Ingresar departamento valido")]
        public int Depto { get; set; }
        public Nullable<int> EstacionamientoV { get; set; }
        public System.DateTime Fingreso { get; set; }
    
        public virtual Departamentos Departamentos { get; set; }
        public virtual Estacionamientos Estacionamientos { get; set; }
    }
}
